backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - name: article
    label: Article
    folder: source/posts/
    extension: .html.md
    format: frontmatter
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - { label: Auteur, name: author, widget: string }
      - { label: Titre, name: title, widget: string }
      - { label: Categorie, name: tags, , widget: "select", options: ["Actualités", "Ateliers"] }
      - { label: Description, name: description, widget: string }
      - { label: Date de publication, name: date, widget: datetime }
      - { label: Image, name: image, widget: image }
      - { label: Article, name: body, widget: markdown }
